NAME: 'BBN.wisdomTeeth.res50.180epoch.testfinal2.4'
OUTPUT_DIR: '../output/wisdomTeeth'
SHOW_STEP: 500
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (140, 140)
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'wisdomTeethSet'
  DATA_TYPE: 'jpg'
  TRAIN_JSON: '../jsons/wisdomTeeth_train.json'
  VALID_JSON: '../jsons/wisdomTeeth_val.json'

BACKBONE:
  TYPE: 'bbn_res50'

MODULE:
  TYPE: 'GAP'

LOSS:
  LOSS_TYPE: 'CrossEntropy'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

TRAIN:
  BATCH_SIZE: 32
  MAX_EPOCH: 180
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'bbn_mix'
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'
  OPTIMIZER:
    TYPE: 'ADAM'
    BASE_LR: 0.005
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'cosine'
    LR_STEP: [120, 160]
    LR_FACTOR: 0.1
    COSINE_DECAY_END: 30


TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 16
  MODEL_FILE: './models/BBN.wisdomTeeth.res50.180epoch.best_model.pth'

